# Generated by Django 3.2.9 on 2022-01-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('direction', models.CharField(max_length=55)),
                ('subject', models.CharField(max_length=55)),
            ],
        ),
    ]
