# Generated by Django 3.2.9 on 2022-01-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Напровление'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Загрузите фото'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Название'),
        ),
    ]
