# Generated by Django 3.2.9 on 2022-01-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220106_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Название')),
                ('task', models.CharField(max_length=255, verbose_name='Инструкция')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('points', models.IntegerField(blank=True, null=True, verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
