# Generated by Django 3.2.9 on 2022-01-09 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
