# Generated by Django 3.2.9 on 2022-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_tasks_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(max_length=55, null=True, verbose_name='Напровление'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, default='any subject', max_length=55, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=55, verbose_name='Название'),
        ),
    ]
