# Generated by Django 3.2.9 on 2022-01-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220110_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/images/', verbose_name='Загрузите фото'),
        ),
    ]
