# Generated by Django 3.2.9 on 2022-01-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20220112_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='slug',
        ),
    ]
