# Generated by Django 3.2.9 on 2022-01-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_tasks', to='course.course'),
        ),
    ]
