# Generated by Django 3.2.9 on 2022-01-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_course_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
