# Generated by Django 3.2.9 on 2022-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, default='Предмет', max_length=55, verbose_name='Предмет'),
        ),
    ]
